name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-tauri:
    name: CI / Tauri
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Restore Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.system.target }}
          override: true
      - name: Install extra dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt update -y
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  frontend
    name: CI / Vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run Build
        run: yarn build