name: Continuous Delivery / Release

on:
  push:
    tags:
      - '*'

jobs:
  publish-tauri:
    name: CD / Tauri
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set release version
        run: |
          export RELEASE_VERSION="${GITHUB_TAG:1}"
          echo "Version: ${{ env.RELEASE_VERSION }}"
          echo "Tag: ${{ env.GITHUB_TAG }}"
          ./scripts/bump.sh ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TAG: ${{ github.event.release.tag_name }}
      
      - name: Setup Node
        uses: josh-development/.github/setup-node@main

      - name: Restore Cargo Cache
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Tweak package.json
        run: python3 -c "import os; import json; p = json.load(open('package.json')); p['version'] = os.environ['RELEASE_VERSION']; json.dump(p, open('package.json', 'w'), indent=2, ensure_ascii=False);"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.system.target }}
          override: true

      - name: Install extra dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt update -y
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Build Tauri App
        run: yarn tauri build

      - name: Build PKGBUILD
        run: ./scripts/build.sh

      - name: Upload release asset
        run: |
          gh release upload ${{ env.RELEASE_VERSION }} "$(find ./build -name *.deb)" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: parrot-bin
          pkgbuild: ./build/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519